import '../models/weather.model.dart';

final dummy = WeatherModel(
  localTime: DateTime.now(),
  lastUpdated: DateTime.now(),
  location: "Loading",
  temp: 25,
  feelsLike: 28,
  condition: "Sunny",
  conditionImage: "suny",
  wind: 10.5,
  humidity: 65,
  forecast: [
    WeatherModel(
      localTime: DateTime.now().add(const Duration(days: 1)),
      lastUpdated: DateTime.now(),
      location: "Cityville",
      temp: 28,
      feelsLike: 30,
      condition: "Partly Cloudy",
      conditionImage: "partly_cloudy_image_url",
      wind: 12.0,
      humidity: 60,
      forecast: null,
    ),
    WeatherModel(
      localTime: DateTime.now().add(const Duration(days: 2)),
      lastUpdated: DateTime.now(),
      location: "Cityville",
      temp: 26,
      feelsLike: 29,
      condition: "Rainy",
      conditionImage: "rainy_image_url",
      wind: 15.0,
      humidity: 75,
      forecast: null,
    ),
    WeatherModel(
      localTime: DateTime.now().add(const Duration(days: 3)),
      lastUpdated: DateTime.now(),
      location: "Cityville",
      temp: 23,
      feelsLike: 25,
      condition: "Cloudy",
      conditionImage: "cloudy_image_url",
      wind: 8.0,
      humidity: 70,
      forecast: null,
    ),
    WeatherModel(
      localTime: DateTime.now().add(const Duration(days: 4)),
      lastUpdated: DateTime.now(),
      location: "Cityville",
      temp: 30,
      feelsLike: 32,
      condition: "Sunny",
      conditionImage: "sunny_image_url",
      wind: 10.0,
      humidity: 55,
      forecast: null,
    ),
  ],
);
